services:
  postgres-db:
    container_name: db_policia
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data-police:/var/lib/postgresql/data
volumes:
  pg-data-police: